module.exports = {
  SCENES: {
    LIST: "list",
    DIARY: "diary",
    RECORD: "record",
    FIND_BY_TAG: "findByTag",
    FIND_BY_DATE: "findByDate",
    FIND_All: "findAll",
    WEATHER: "weather",
  },
  BUTTONS: {
    CREATE_LIST: "📝 Create list",
    NEW_RECORD: "📓 New rec to diary",
    FIND: "🔎 Find rec",
    WEATHER: "🌦 Weather",
    FIND_BY_TAG: "#⃣ Find by tag",
    FIND_BY_DATE: "📅 Find by date",
    FIND_All: "🗂 Find all records",
    DELETE_LIST: "❌ Delete list",
    DELETE_MESSAGE: "❌ Delete message",
    BACK: "🔙 Back",
    HIDE_MESSAGE: "Thank you",
    DELETE_THIS_REC: "Delete this record",
  },
  INLINE_BUTTONS: {
    DELETE_RECORD: "dR",
    DELETE_LAST_REC: "dLR",
    HIDE_REC: "hide",
  },
};
